// tslint:disable
import * as React from "react";

export class AsyncComponent extends React.Component {
    render() {
        return (
            <div>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ut accumsan neque ut enim imperdiet, vel elementum lorem efficitur. Nullam porttitor vel elit feugiat aliquam. Proin suscipit turpis lacus, eu venenatis nibh ultrices eget. Donec non euismod nunc. Donec malesuada feugiat nulla in euismod. Aliquam vel neque aliquam, rutrum diam eu, tincidunt dui. Praesent consequat eget purus vitae luctus. Aliquam porttitor luctus libero et bibendum. Integer at lectus vitae sem gravida lacinia. Morbi nec volutpat nibh. Maecenas malesuada augue sit amet pharetra vehicula. Vestibulum lobortis, metus eu imperdiet facilisis, neque magna dignissim lorem, non rhoncus nibh sapien ut ligula. Nunc in aliquam massa, eget fermentum tellus. Nam tempus nulla nunc, ut gravida nibh pretium id. Praesent condimentum ligula sit amet lectus sagittis ullamcorper at a lacus.</p>
                <p>Proin rutrum ornare leo ac dapibus. Aenean lobortis velit eu efficitur condimentum. Aliquam vitae felis tempus, tempus libero bibendum, commodo purus. Nam at tortor nec justo pharetra auctor eget eget velit. Mauris at maximus dolor, eu tincidunt augue. Maecenas vulputate nulla elit. Vivamus aliquet rutrum interdum. Sed id tellus quis tortor luctus maximus. Phasellus id odio in erat molestie volutpat non ut purus. Nullam posuere tortor ut elit mattis sagittis. Pellentesque eget placerat orci. Donec quis consequat ex, at convallis nisl. Aliquam tristique mi nulla, at faucibus orci porta ut. Cras condimentum, neque id venenatis viverra, nibh eros efficitur odio, sit amet egestas est nulla sed neque.</p>
                <p>Suspendisse rhoncus semper ipsum pellentesque lobortis. Fusce non pharetra enim. Ut commodo lacinia orci non sagittis. Quisque tempor velit ut bibendum vulputate. Quisque auctor ut ligula a porttitor. Pellentesque iaculis elit arcu, eu consectetur risus pulvinar vitae. Aliquam in maximus dolor, non feugiat magna. Etiam faucibus sem vitae diam ullamcorper, in molestie ipsum viverra. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc quam augue, ornare ac auctor ut, maximus eget nunc. Vivamus sit amet mattis urna. Donec maximus hendrerit pharetra.</p>
                <p>Vivamus vestibulum, magna ut tincidunt aliquam, erat erat blandit turpis, sit amet ornare elit nulla ut magna. Sed egestas arcu ac ligula vehicula, et tempor lectus convallis. Nam a mauris lacinia, fermentum lacus quis, rutrum eros. Vivamus quam nisi, porttitor sed lectus vel, laoreet venenatis purus. Aliquam tempus eros at nulla eleifend tempor. Mauris efficitur justo eros, vel lobortis nibh mattis maximus. Maecenas nisl libero, vestibulum in velit non, tincidunt mattis risus. Quisque porta rhoncus lacus, eget elementum metus tincidunt in.</p>
                <p>Integer viverra nisi nisl, eget porta ipsum ultricies nec. Nam porttitor mollis congue. Donec eget hendrerit magna. Duis at pharetra odio. Maecenas lobortis, sapien vel mollis tempus, enim arcu posuere libero, a ornare dui nulla et lectus. Nam a dapibus magna. Praesent imperdiet bibendum ex, a vehicula elit porta at. Vivamus non volutpat tellus. Ut auctor sed sem ac pharetra. Sed interdum, libero fringilla ultrices lobortis, mauris ante blandit dolor, convallis pretium mi nisl nec odio. Sed faucibus urna a convallis mollis. Etiam ut felis in arcu feugiat sodales eget vel felis. Sed semper ac nulla quis lacinia. Vestibulum eleifend purus eget pharetra convallis.</p>
            </div>
        );
    }
}